### ISSUE TITLE
Wrong characters in coloured buttons

### ISSUE THREAD

**Issue by pdario** [nerone-github/WebViewAuto#15]
Hello, it is some time now that I have a wrong charset in the "coloured" buttons, the one around the URL field and those in the keyboard view; I tried removing and installing the app back, but nothing changed.

What can I do?

**Comment by nerone-github** [comment]
Hi more info please. Android Version, Phone, Maybe screenshot or photo too. Thanks

**Comment by pdario** [comment]
Galaxy S8+
Android 7.0
I can't take photos while the phone is connected... You know the 4 buttons beside the URL field? They contain characters from some eastern map, I could say it is japanese.

Tnx

**Comment by nerone-github** [comment]
latest apk from yesterday? You could try to make a shot by unlocking the phone or using the android auto emulator on the pc. (To unlock press Taskmanager button then home , afterwards you can enter camera during AA session)

**Comment by pdario** [comment]
Ok, the latest APK works correctly.
BTW: I don't have a physical task manager button, I just can "hard" press in the home button area to get a navigation bar that does not contain the task manager button.

Can you explain how to use the "send to car" function on the mobile app? Is it intended to be used unlocking the phone while connected?

**Comment by nerone-github** [comment]
Yea it is intended to be used unlocking the phone when connected. Then try to longpress then single peess home button.
