### ISSUE TITLE
GPS position in Browser

### ISSUE THREAD

**Issue by rotepappnase** [nerone-github/WebViewAuto#20]
Please allow to use the Phone Position for webpages (Like mm.blitzer.de)

**Comment by nerone-github** [comment]
Hey, didnt know about this site :D Nice! I have commited a change which should make it possible to share the geolocation. However you need to manually grant the Location permission within the app.

Let me know if it works please!

![image](https://user-images.githubusercontent.com/10217641/35775761-6d494cb6-098f-11e8-95fe-38d37445af99.png)

![image](https://user-images.githubusercontent.com/10217641/35775695-13b2a66c-098e-11e8-9ade-442caa36fffd.png)

**Comment by rotepappnase** [comment]
Now it works perfectly. Many thanks for the fast Implementation! :)
