### ISSUE TITLE
Lacking Photo Art

### ISSUE THREAD

**Issue by bigblockentmt** [nerone-github/WebViewAuto#21]
Photo Art it not getting shown

**Comment by nerone-github** [comment]
It seems you are not using the latest version. Please install the latest apk

**Comment by bigblockentmt** [comment]
Just put the new app on my Samsung S8+ and I now have the correct icon in the book mark area but still unable to see the channel logo.. Thanks

Also if I want to hear the music I have to first go to the AA music and play for a sec and pause and then go back to your app.

**Comment by bigblockentmt** [comment]
This is not Invalid as there is something still wrong. I'm just trying to let you know.

**Comment by nerone-github** [comment]
Well it is invalid since you were using an old APK ;-) 

Please open a separate issue with **detailed** description for each error. Sorry if i'm nagging you but else it will be chaos and it is impossible to work on the issues.

**Comment by nerone-github** [comment]
Also i cannot confirm the error since i don't have an account for that site

**Comment by bigblockentmt** [comment]
how about I give you a code
