### ISSUE TITLE
Site specific problem with SiriusXM - No logo

### ISSUE THREAD

**Issue by bigblockentmt** [nerone-github/WebViewAuto#22]
New app version on my Samsung S8+ and I now have the correct icon in the book mark area but still unable to see the channel logo.. Thanks

**Comment by nerone-github** [comment]
This problem is due to a implementation error on their site

![image](https://user-images.githubusercontent.com/10217641/35937803-9c1a3b80-0c47-11e8-918a-04d9cae0f6f0.png)

02-07 20:41:09.483 25854-25854/org.openauto.webviewauto I/chromium: [INFO:CONSOLE(0)] "Mixed Content: The page at 'https://player.siriusxm.ca/#/player/live' was loaded over HTTPS, but requested an insecure image 'http://pri.art.prod.streaming.siriusxm.com/images/channel/20180201/8208-1-17-00-80x80.png'. This request has been blocked; the content must be served over HTTPS.", source: https://player.siriusxm.ca/#/player/live (0)

They have to load the image via https as well

I will check if this is possible to change for WebView - But if it is not possible then this won't work until they fix their error.

**Comment by nerone-github** [comment]
I have now set:

webView.getSettings().setMixedContentMode(WebSettings.MIXED_CONTENT_COMPATIBILITY_MODE);

https://stackoverflow.com/questions/32155634/android-webview-not-loading-mixed-content

So after updating the apk this should work ;)

**Comment by bigblockentmt** [comment]
Sounds great, cant wait to see if there is something that can be done.

I see in the picture that its working for you. Did you do something to
allow the permission or are you using the computer?

**Comment by bigblockentmt** [comment]
where would I get the new update?

**Comment by nerone-github** [comment]
Apk link: https://github.com/nerone-github/WebViewAuto/tree/master/apk

**Comment by bigblockentmt** [comment]
OMG it worked. Are you in Canada or US? $$

**Comment by bigblockentmt** [comment]
Sent you a coffee for your hard work

**Comment by nerone-github** [comment]
Where, don't worry. No need to ;)

**Comment by bigblockentmt** [comment]
Sent to your email


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: nerone-github <notifications@github.com> Date: 2018-02-07  10:49 PM  (GMT-05:00) To: nerone-github/WebViewAuto <WebViewAuto@noreply.github.com> Cc: bigblockentmt <jessedeslauriers84@gmail.com>, Author <author@noreply.github.com> Subject: Re: [nerone-github/WebViewAuto] Site specific problem with SiriusXM - No logo (#22) 
Where, don't worry. No need to ;)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nerone-github/WebViewAuto","title":"nerone-github/WebViewAuto","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nerone-github/WebViewAuto"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nerone-github in #22: Where, don't worry. No need to ;)"}],"action":{"name":"View Issue","url":"https://github.com/nerone-github/WebViewAuto/issues/22#issuecomment-363994173"}}}

**Comment by nerone-github** [comment]
If you can please get the money back i dont have any email

**Comment by bigblockentmt** [comment]
The first email you sent me 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: nerone-github <notifications@github.com> Date: 2018-02-08  7:16 AM  (GMT-05:00) To: nerone-github/WebViewAuto <WebViewAuto@noreply.github.com> Cc: bigblockentmt <jessedeslauriers84@gmail.com>, Author <author@noreply.github.com> Subject: Re: [nerone-github/WebViewAuto] Load http resources when site is https (#22) 
If you can please get the money back i dont have any email

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nerone-github/WebViewAuto","title":"nerone-github/WebViewAuto","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nerone-github/WebViewAuto"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nerone-github in #22: If you can please get the money back i dont have any email"}],"action":{"name":"View Issue","url":"https://github.com/nerone-github/WebViewAuto/issues/22#issuecomment-364094439"}}}

**Comment by nerone-github** [comment]
As said i dont have any method set up to gather money so whatever you sent it went down the drain. If you can ask refund and donate that amount to a cancer research or whatever ;)

**Comment by bigblockentmt** [comment]
Ok Still thanks for everything!
