### ISSUE TITLE
Use Commander or dial switch Audi Mazda 

### ISSUE THREAD

**Issue by bigblockentmt** [nerone-github/WebViewAuto#24]
Would like to use the MMI or Commander switch to scroll through the screen. 

Screen locks when driving. My wife passenger is unable to use the webViewAuto screen. 

Using this on 2014 - 2018 Mazda CX5 with commander switch

Also 2016 - 2018 Audi Q5 MMI Switch to scroll

**Comment by nerone-github** [comment]
Not possible since there is no public API, 
And use while car is moving is not intended
your wife should use the phone for browsing so you wont get distracted  ;)
or get a car which doesn't lock the touchscreen
