### ISSUE TITLE
Full-Screen support for HTML5 Video

### ISSUE THREAD

**Issue by nerone-github** [nerone-github/WebViewAuto#6]

**Comment by kaisertgc** [comment]
Hi,
I am not a developer but this guys application workin fine and giving fullscreen support on videos.

https://github.com/thekirankumar/youtube-android-auto/

Maybe somehow his codes can help. And as I understand he is using 
https://github.com/cprcrack/VideoEnabledWebView   as his basement. Your app is very usefull would like to see fullscreen support. Cheers.

**Comment by nerone-github** [comment]
Done ;-)

**Comment by kaisertgc** [comment]
You the best man. I am at bar now
 Car sitting outside. This shot for you.
