### ISSUE TITLE
Android Auto Settings - WebViewAuto

### ISSUE THREAD

**Issue by u1200a** [nerone-github/WebViewAuto#8]
I Can't find the developer settings in my Android Auto! (2.8.574513-release)
I Can find only the Help&feedback and Send Feedback possibilities.

It means I Can't these settings;

•Enable Developer settings in Android Auto
•Enable 'Unknown sources' checkbox

Hi!

u1200a from Hungary

**Comment by nerone-github** [comment]
hi when it says tap here you must tap a few times until it enables

https://raw.githubusercontent.com/nerone-github/LocalSpeedcam/master/images/devsettings.png
