### ISSUE TITLE
Enter button doesn't work after last update

### ISSUE THREAD

**Issue by kaisertgc** [nerone-github/WebViewAuto#9]
After putting adress top right button seems Enter button. Should push it and open the page but it doesnt. How to open the page after new adress? Appreciate your works. Thanks.

VW passat 2017, android auto latest version, android 7.1
Video: https://drive.google.com/file/d/14m_NqBin5_jHYhTJtAAfWpkgQtbxOFa7/view?usp=drivesdk

**Comment by nerone-github** [comment]
Hi try to use the enter button on the keyboard when changing the url. the top button is for page submit. I know it is confusing, will try to improve usability soon and maybe also create a better instructions page

**Comment by houmles** [comment]
I have a same problem. Clicking submit button on top doing nothing.

**Comment by nerone-github** [comment]
the submit button is for submitting a form on a website after text was entered. it is only needed when a page does not have a submit button

**Comment by bobybc** [comment]
Submit button does not work if you enter ne adress

**Comment by houmles** [comment]
Ah, ok ..but enter doesn't work either for me.
I can browse only from Favorites or by clicking on links. No manual URL.

**Comment by kaisertgc** [comment]
I will try tomorrow but as i remember enter button on keyboard just puts adress to adress bar. When you click on keyboard enter button, it doesnt open also.

**Comment by nerone-github** [comment]
I have changed various things now, so this issue should be fixed. If still problems occur please re-open new issues to avoid confusion.

- Now the keyboard will always use up the whole screen, and there will be only one "Enter" button - in URL input mode, and in text-input mode the usage is the same. 

- The Menu (top bar) submit button is only to submit the form on a website

**Comment by kaisertgc** [comment]
Thanks for your efforts. I will try first thing in the morning and write my comments. I hope you will keep up your good work on this project.

**Comment by kaisertgc** [comment]
Thanks for your efforts. I will try first thing in the morning and write my comments. I hope you will keep up your good work on this project.

**Comment by houmles** [comment]
I can confirm it is working. Thanks

**Comment by kaisertgc** [comment]
Working nicely. Thanks much.
